config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-buff-cattle.sh
        container: qc.acc_squirrely-gold-turtle
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-persimmon-centipede.sh
        container: qc.doc_tacky-dandelion-discus
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-fuchsia-armadillo.sh
        container: qc.doc_shabby-chartreuse-russel
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-whale.sh
        container: qc.doc_skanky-plum-iguana
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pink-ocelot.sh
        container: qc.lic_goopy-copper-raccoon
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-goldenrod-barracuda.sh
        container: qc.met_flaky-gold-tortoise
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-xanthic-argentino.sh
        container: qc.sec_lanky-razzmatazz-oyster
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pear-hornet.sh
        container: qc.sty_pasty-salmon-vulture
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-wallaby.sh
        container: qc.sty_shaky-amber-dugong
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-green-jackal.sh
        container: qc.sty_flaky-blue-wolverine
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-dachshund.sh
        container: qc.uni_scummy-denim-uguisu
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tomato-buzzard.sh
        container: qc.ver_snoopy-plum-argentino
timeout: 5400
