config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cyan-frise.sh
        container: qc.acc_chewy-coral-cockroach
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cardinal-lizard.sh
        container: qc.doc_flimsy-pear-neanderthal
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-blue-moorhen.sh
        container: qc.doc_sleazy-malachite-swan
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-persimmon-crocodile.sh
        container: qc.doc_foggy-gold-monkey
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-beige-antelope.sh
        container: qc.lic_gloppy-purple-forest
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-chestnut-seal.sh
        container: qc.met_geeky-persimmon-wolverine
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-grey-mayfly.sh
        container: qc.sec_hasty-corn-seahorse
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-asparagus-newt.sh
        container: qc.sty_woozy-russet-setter
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-purple-mandrill.sh
        container: qc.sty_crabby-burgundy-molly
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-orange-squirrel.sh
        container: qc.sty_tasty-champagne-wolverine
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amethyst-raccoon.sh
        container: qc.uni_scummy-cyan-havanese
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-dandelion-mandrill.sh
        container: qc.ver_slimy-orchid-dachsbracke
timeout: 5400
