config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-salmon-sponge.sh
        container: qc.acc_cranky-sepia-coyote
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-heliotrope-crab.sh
        container: qc.doc_messy-aquamarine-devil
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-carmine-hyena.sh
        container: qc.doc_hasty-amethyst-dollar
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ivory-monster.sh
        container: qc.doc_sleepy-alizarin-kakapo
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-wisteria-otter.sh
        container: qc.lic_seedy-apricot-hound
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-razzmatazz-woodlouse.sh
        container: qc.met_skanky-cyan-jaguar
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-aquamarine-maltese.sh
        container: qc.sec_beady-magenta-dunker
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-smalt-bison.sh
        container: qc.sty_greasy-amaranth-chin
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-puce-dragonfly.sh
        container: qc.sty_squeaky-myrtle-caterpillar
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-red-bobcat.sh
        container: qc.sty_snippy-jade-snail
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-fuchsia-armadillo.sh
        container: qc.uni_freaky-scarlet-cattle
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-lavender-malamute.sh
        container: qc.ver_whiny-aqua-fish
timeout: 5400
