config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-azure-caiman.sh
        container: qc.acc_skimpy-periwinkle-gopher
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-turquoise-beetle.sh
        container: qc.doc_foggy-amethyst-eleuth
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-aquamarine-centipede.sh
        container: qc.doc_zippy-champagne-cassowary
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-saffron-hornet.sh
        container: qc.doc_woozy-burgundy-cow
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-olivine-jackal.sh
        container: qc.lic_paltry-beige-rattlesnake
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ochre-pig.sh
        container: qc.met_cozy-green-maltese
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-apricot-dragonfly.sh
        container: qc.sec_stinky-firebrick-spoonbill
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-carmine-monkey.sh
        container: qc.sty_thirsty-thistle-robin
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cinnamon-coati.sh
        container: qc.sty_jumpy-chartreuse-indri
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chocolate-termite.sh
        container: qc.sty_wimpy-eggplant-tzu
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-charcoal-kingfisher.sh
        container: qc.uni_shaggy-puce-hippopotamus
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-charcoal-bulldog.sh
        container: qc.ver_shaggy-azure-mastiff
timeout: 5400
