config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-seashell-bonobo.sh
        container: qc.acc_jumpy-scarlet-gopher
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-magenta-heron.sh
        container: qc.doc_silly-champagne-beetle
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-heliotrope-camel.sh
        container: qc.doc_geeky-gamboge-dolphin
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-cassowary.sh
        container: qc.doc_fuzzy-xanthic-molly
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-green-hare.sh
        container: qc.lic_snappy-salmon-hare
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-emerald-cichlid.sh
        container: qc.sec_thirsty-magnolia-schnauzer
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-blue-dalmatian.sh
        container: qc.sty_lousy-white-sloth
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-zucchini-baboon.sh
        container: qc.sty_squeaky-rust-schnauzer
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-wisteria-starfish.sh
        container: qc.sty_gummy-beige-robin
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-seashell-budgerigar.sh
        container: qc.uni_hazy-copper-tortoise
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cyan-devil.sh
        container: qc.ver_sleepy-coral-owl
timeout: 5400
