config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-periwinkle-anteater.sh
        container: qc.acc_bluesy-silver-hummingbird
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-eggplant-sparrow.sh
        container: qc.doc_surly-ivory-husky
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-corn-macaw.sh
        container: qc.doc_boozy-malachite-grouse
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-sapphire-paradise.sh
        container: qc.doc_flimsy-amaranth-hummingbird
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-ruby-bracke.sh
        container: qc.lic_muzzy-rose-hippopotamus
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wisteria-moth.sh
        container: qc.met_zippy-wisteria-ray
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-salmon-echidna.sh
        container: qc.sec_skinny-tan-vulture
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ecru-tiger.sh
        container: qc.sty_zippy-lilac-elephant
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-bistre-shrew.sh
        container: qc.sty_squeaky-cream-goose
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-black-chameleon.sh
        container: qc.sty_zippy-corn-falcon
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-periwinkle-moose.sh
        container: qc.uni_ugly-gamboge-squid
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cinnabar-oyster.sh
        container: qc.ver_trippy-sapphire-turkey
timeout: 5400
