config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-coral-saola.sh
        container: qc.acc_shaky-cyan-owl
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-magenta-centipede.sh
        container: qc.doc_snoopy-myrtle-havanese
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-thistle-barb.sh
        container: qc.doc_baggy-tangerine-emu
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-khaki-dugong.sh
        container: qc.doc_clammy-russet-bombay
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-xanthic-alligator.sh
        container: qc.lic_gloppy-firebrick-dachshund
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-blue-buzzard.sh
        container: qc.met_pokey-zucchini-hamster
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gold-lemming.sh
        container: qc.sec_woozy-cinnamon-numbat
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-champagne-beaver.sh
        container: qc.sty_snoopy-xanthic-whippet
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-malachite-otter.sh
        container: qc.sty_cranky-cerise-dachsbracke
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-olive-dollar.sh
        container: qc.sty_trippy-copper-lizard
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-salmon-uakari.sh
        container: qc.uni_seedy-vermilion-drever
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-apricot-seal.sh
        container: qc.ver_hasty-white-turkey
timeout: 5400
