config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-lime-zebra.sh
        container: qc.acc_lovely-auburn-caterpillar
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-denim-sponge.sh
        container: qc.doc_droopy-thistle-havanese
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-puce-lionfish.sh
        container: qc.doc_woolly-chartreuse-akbash
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-persimmon-otter.sh
        container: qc.doc_sleazy-peach-anteater
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chestnut-giraffe.sh
        container: qc.lic_sunny-chocolate-bat
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ivory-affenpinscher.sh
        container: qc.met_nerdy-mauve-retriever
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ultramarine-butterfly.sh
        container: qc.sec_lanky-rose-chameleon
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-ultramarine-armadillo.sh
        container: qc.sty_grumpy-cinnamon-armadillo
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-champagne-collie.sh
        container: qc.sty_wheezy-tan-olm
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-flax-dolphin.sh
        container: qc.sty_slimy-xanthic-quokka
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-alizarin-zonkey.sh
        container: qc.uni_snappy-cornflower-avocet
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rust-mule.sh
        container: qc.ver_blurry-alizarin-ant
timeout: 5400
