config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-platinum-millipede.sh
        container: qc.acc_grumpy-pear-tiger
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-orchid-dane.sh
        container: qc.doc_smelly-blue-meerkat
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-mustard-dunker.sh
        container: qc.doc_foggy-dandelion-oriole
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-saffron-wrasse.sh
        container: qc.doc_grumpy-viridian-shrew
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-aquamarine-quail.sh
        container: qc.lic_greasy-myrtle-wombat
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-tomato-earwig.sh
        container: qc.met_flimsy-olive-burmese
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-plum-coyote.sh
        container: qc.sec_snazzy-corn-starfish
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-auburn-chipmunk.sh
        container: qc.sty_thirsty-chartreuse-bulldog
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gamboge-terrier.sh
        container: qc.sty_ugly-dandelion-cat
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-blue-heron.sh
        container: qc.sty_freaky-brass-akbash
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cyan-starfish.sh
        container: qc.uni_nippy-tan-hare
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-aquamarine-gorilla.sh
        container: qc.ver_pretty-smalt-hyrax
timeout: 5400
