config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ultramarine-snail.sh
        container: qc.acc_sloppy-persimmon-impala
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cinnabar-bee.sh
        container: qc.doc_scanty-ruby-mau
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-emerald-antelope.sh
        container: qc.doc_hasty-lilac-wasp
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amaranth-bullfrog.sh
        container: qc.doc_wheezy-carmine-numbat
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-fuchsia-ragdoll.sh
        container: qc.lic_paltry-champagne-beetle
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sepia-dog.sh
        container: qc.met_droopy-myrtle-stingray
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-bronze-flamingo.sh
        container: qc.sec_hazy-cerulean-cuscus
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-alizarin-cougar.sh
        container: qc.sty_messy-jade-tamarin
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-taupe-chamois.sh
        container: qc.sty_dorky-chartreuse-crocodile
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-malachite-barnacle.sh
        container: qc.sty_nerdy-champagne-markhor
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mauve-barb.sh
        container: qc.uni_flabby-russet-angora
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-denim-cat.sh
        container: qc.ver_sleazy-seashell-bandicoot
timeout: 5400
