config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-black-donkey.sh
        container: qc.acc_baggy-rust-beagle
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lavender-orangutan.sh
        container: qc.doc_jumpy-chestnut-serval
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-green-moth.sh
        container: qc.doc_bumpy-denim-salamander
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-green-lynx.sh
        container: qc.doc_craggy-magnolia-molly
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-champagne-caterpillar.sh
        container: qc.lic_foggy-silver-barb
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-harlequin-robin.sh
        container: qc.sec_ugly-silver-zebu
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-sapphire-antelope.sh
        container: qc.sty_hilly-gold-tortoise
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-xanthic-bombay.sh
        container: qc.sty_wheezy-cobalt-moose
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-jade-mouse.sh
        container: qc.sty_pokey-eggplant-baboon
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-turquoise-hornet.sh
        container: qc.uni_ready-wisteria-tetra
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lime-gecko.sh
        container: qc.ver_crabby-smalt-fowl
timeout: 5400
