config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-peach-ray.sh
        container: qc.acc_randy-charcoal-meerkat
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-gold-lemur.sh
        container: qc.doc_skinny-seashell-wolverine
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lavender-squid.sh
        container: qc.doc_sickly-khaki-okapi
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-indigo-magpie.sh
        container: qc.doc_skanky-vermilion-rhinoceros
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cornflower-maltese.sh
        container: qc.lic_gimpy-eggplant-barnacle
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-platinum-falcon.sh
        container: qc.met_shaky-green-cuttlefish
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lime-insect.sh
        container: qc.sec_scanty-tan-tang
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-charcoal-chow.sh
        container: qc.sty_cloudy-gamboge-lizard
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-platinum-wrasse.sh
        container: qc.sty_scanty-ivory-buffalo
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-grey-abyssinian.sh
        container: qc.sty_goopy-azure-dragonfly
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.surly-wheat-foxhound.sh
        container: qc.uni_smelly-olive-serval
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-flax-camel.sh
        container: qc.ver_crappy-gamboge-peccary
timeout: 5400
