config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-tomato-fowl.sh
        container: qc.acc_gimpy-jade-burmese
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-rose-zebu.sh
        container: qc.doc_thirsty-crimson-starfish
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lilac-mandrill.sh
        container: qc.doc_fuzzy-alizarin-clam
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-gold-gecko.sh
        container: qc.doc_flaky-viridian-barnacle
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-myrtle-stingray.sh
        container: qc.lic_silly-magnolia-gar
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-peach-beetle.sh
        container: qc.met_greasy-saffron-labradoodle
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-mauve-molly.sh
        container: qc.sec_bluesy-purple-jellyfish
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olivine-mist.sh
        container: qc.sty_jumpy-peach-buzzard
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-olive-capuchin.sh
        container: qc.sty_thirsty-denim-guppy
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cinnabar-vole.sh
        container: qc.sty_queasy-aqua-stoat
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-olive-goat.sh
        container: qc.uni_cozy-brass-audemer
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-emerald-sheepdog.sh
        container: qc.ver_snazzy-jade-dormouse
timeout: 5400
