config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cerfacs-globc/xtclim:
      branch: master
      repo: https://github.com/cerfacs-globc/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cerfacs-globc/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-lavender-affenpinscher.sh
        container: qc.acc_sleepy-orchid-sponge
  QC.Doc:
    repos:
      github.com/cerfacs-globc/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-crimson-burmese.sh
        container: qc.doc_greasy-chestnut-dhole
      github.com/cerfacs-globc/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-zonkey.sh
        container: qc.doc_skinny-heliotrope-slug
  QC.Lic:
    repos:
      github.com/cerfacs-globc/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-olivine-wolfhound.sh
        container: qc.lic_squeaky-violet-chamois
  QC.Ver:
    repos:
      github.com/cerfacs-globc/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cobalt-tzu.sh
        container: qc.ver_flimsy-magenta-fly
timeout: 5400
