config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-fuchsia-hippopotamus.sh
        container: qc.acc_slaphappy-blue-flamingo
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-silver-shrew.sh
        container: qc.doc_pretty-maroon-octopus
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-charcoal-worm.sh
        container: qc.doc_shaggy-gold-zebu
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-pumpkin-beagle.sh
        container: qc.doc_whiny-burgundy-blue
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-olivine-tiger.sh
        container: qc.lic_hazy-cream-serval
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-salmon-husky.sh
        container: qc.met_cloudy-chocolate-sheep
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-asparagus-balinese.sh
        container: qc.sec_fuzzy-lavender-pinscher
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cerulean-shrew.sh
        container: qc.sty_seedy-asparagus-shrimp
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pear-dalmatian.sh
        container: qc.sty_bumpy-heliotrope-tetra
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-copper-rabbit.sh
        container: qc.sty_grumpy-dandelion-peccary
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chestnut-camel.sh
        container: qc.uni_wimpy-jade-fousek
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-amaranth-wolfhound.sh
        container: qc.ver_smelly-cyan-okapi
timeout: 5400
