config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-wisteria-chinchilla.sh
        container: qc.acc_whiny-salmon-blue
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-wheat-fox.sh
        container: qc.doc_sleazy-gamboge-malamute
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-asparagus-panda.sh
        container: qc.doc_thirsty-tan-chimpanzee
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-zucchini-turtle.sh
        container: qc.doc_paltry-buff-newt
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-asparagus-forest.sh
        container: qc.lic_nerdy-gamboge-vole
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-linen-quokka.sh
        container: qc.met_gimpy-taupe-squirt
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-carmine-weasel.sh
        container: qc.sec_woolly-asparagus-jellyfish
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ruby-schnauzer.sh
        container: qc.sty_sloppy-amethyst-spitz
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chestnut-ocelot.sh
        container: qc.sty_stuffy-puce-mouse
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-denim-gerbil.sh
        container: qc.sty_gimpy-chartreuse-wolverine
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-platinum-mongrel.sh
        container: qc.uni_trippy-gold-guppy
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-dandelion-shrew.sh
        container: qc.ver_chummy-purple-spaniel
timeout: 5400
