config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chestnut-corgi.sh
        container: qc.acc_stinky-auburn-mist
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chartreuse-drever.sh
        container: qc.doc_pasty-brass-akita
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-indigo-chow.sh
        container: qc.doc_seedy-platinum-seahorse
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cardinal-macaque.sh
        container: qc.doc_scanty-cinnamon-capuchin
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-white-hound.sh
        container: qc.lic_foggy-linen-scorpion
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-rust-octopus.sh
        container: qc.met_zippy-black-rottweiler
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-maroon-armadillo.sh
        container: qc.sec_lumpy-blue-avocet
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-harlequin-chinook.sh
        container: qc.sty_clammy-pink-cougar
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lemon-crocodile.sh
        container: qc.sty_pasty-apricot-tamarin
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-periwinkle-toucan.sh
        container: qc.sty_breezy-cinnabar-quetzal
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-emerald-hyena.sh
        container: qc.uni_pretty-celadon-beaver
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-denim-tuatara.sh
        container: qc.ver_dorky-cinnamon-centipede
timeout: 5400
