config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amaranth-oyster.sh
        container: qc.acc_surly-cinnabar-zorse
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-indigo-caterpillar.sh
        container: qc.doc_goopy-bronze-retriever
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-scarlet-wallaby.sh
        container: qc.doc_wheezy-razzmatazz-weasel
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-firebrick-fish.sh
        container: qc.doc_sickly-gold-chimpanzee
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-chartreuse-sloth.sh
        container: qc.lic_sleepy-cornflower-blue
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-violet-macaw.sh
        container: qc.met_hazy-mustard-lizard
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-celadon-forest.sh
        container: qc.sec_scanty-corn-affenpinscher
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-gold-ragdoll.sh
        container: qc.sty_shaky-emerald-dunker
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-black-coyote.sh
        container: qc.sty_clammy-linen-bear
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-coral-yak.sh
        container: qc.sty_homely-tomato-slug
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ecru-kiwi.sh
        container: qc.uni_ugly-silver-hippopotamus
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chestnut-rhinoceros.sh
        container: qc.ver_skimpy-sapphire-rat
timeout: 5400
