config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-orchid-dugong.sh
        container: qc.acc_ugly-tan-frog
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-olive-bonobo.sh
        container: qc.doc_hasty-linen-dogfish
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-teal-badger.sh
        container: qc.doc_flabby-harlequin-ragdoll
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cerulean-binturong.sh
        container: qc.doc_stinky-chartreuse-sheepdog
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-yellow-ocelot.sh
        container: qc.lic_scummy-ecru-termite
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-brown-seahorse.sh
        container: qc.met_silly-bronze-gecko
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amethyst-eagle.sh
        container: qc.sec_zippy-rose-ocelot
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cerise-whippet.sh
        container: qc.sty_wheezy-magenta-forest
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-fuchsia-camel.sh
        container: qc.sty_sunny-harlequin-collie
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-tomato-affenpinscher.sh
        container: qc.sty_slimy-cinnabar-whippet
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-silver-chow.sh
        container: qc.uni_stealthy-cinnamon-octopus
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-eggplant-macaque.sh
        container: qc.ver_foggy-platinum-worm
timeout: 5400
