config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-peach-neanderthal.sh
        container: qc.acc_squeaky-pink-warthog
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-dandelion-skunk.sh
        container: qc.doc_muzzy-mauve-sheepdog
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-periwinkle-chinook.sh
        container: qc.doc_stealthy-blue-lemur
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cinnabar-abyssinian.sh
        container: qc.doc_snappy-silver-whale
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-rust-whippet.sh
        container: qc.lic_dorky-lemon-woodlouse
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-wheat-fousek.sh
        container: qc.met_geeky-brown-tetra
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-turquoise-leopard.sh
        container: qc.sec_flaky-auburn-spitz
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-goldenrod-stingray.sh
        container: qc.sty_pasty-peach-sheepdog
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rust-terrier.sh
        container: qc.sty_squirrely-eggplant-spaniel
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lilac-moorhen.sh
        container: qc.sty_messy-scarlet-mayfly
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-blue-angelfish.sh
        container: qc.uni_ugly-smalt-shrew
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sepia-spoonbill.sh
        container: qc.ver_flabby-buff-hornet
timeout: 5400
