config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-violet-toucan.sh
        container: qc.acc_surly-apricot-barb
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-auburn-cattle.sh
        container: qc.doc_snazzy-white-elephant
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ultramarine-heron.sh
        container: qc.doc_thirsty-dandelion-owl
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-auburn-grouse.sh
        container: qc.doc_skinny-russet-chameleon
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-periwinkle-echidna.sh
        container: qc.lic_cloudy-white-termite
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ecru-seal.sh
        container: qc.met_hasty-scarlet-cuttlefish
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-black-badger.sh
        container: qc.sec_boozy-peach-dane
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-sepia-mandrill.sh
        container: qc.sty_gimpy-denim-tzu
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cardinal-snake.sh
        container: qc.sty_sleazy-crimson-wildebeest
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-malachite-russel.sh
        container: qc.sty_beady-chestnut-retriever
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-jade-vole.sh
        container: qc.uni_tacky-celadon-penguin
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-razzmatazz-moth.sh
        container: qc.ver_freaky-indigo-moorhen
timeout: 5400
