config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-chocolate-havanese.sh
        container: qc.acc_scanty-periwinkle-pinscher
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-brass-sloth.sh
        container: qc.doc_woozy-orange-dachsbracke
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-wisteria-bird.sh
        container: qc.doc_scaly-wheat-robin
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-wisteria-frog.sh
        container: qc.doc_breezy-ruby-koala
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-amethyst-dog.sh
        container: qc.lic_fuzzy-vermilion-serval
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-auburn-peccary.sh
        container: qc.met_messy-burgundy-vole
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-chartreuse-lion.sh
        container: qc.sec_frumpy-black-macaque
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-periwinkle-spoonbill.sh
        container: qc.sty_tasty-cerulean-snake
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-amaranth-vulture.sh
        container: qc.sty_craggy-ultramarine-bandicoot
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ivory-saola.sh
        container: qc.sty_dorky-firebrick-birman
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-corn-cow.sh
        container: qc.uni_lanky-thistle-vulture
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-seashell-wolfhound.sh
        container: qc.ver_hasty-xanthic-grouse
timeout: 5400
