config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-persimmon-bison.sh
        container: qc.acc_cozy-copper-clam
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-asparagus-dollar.sh
        container: qc.doc_muzzy-amaranth-dormouse
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-taupe-gerbil.sh
        container: qc.doc_trippy-firebrick-dolphin
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-green-lizard.sh
        container: qc.doc_scanty-periwinkle-starfish
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-corn-blue.sh
        container: qc.lic_squeaky-celadon-terrier
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-lilac-argentino.sh
        container: qc.sec_smelly-asparagus-oriole
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-blue-dhole.sh
        container: qc.sty_shabby-jade-neanderthal
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-asparagus-koala.sh
        container: qc.sty_sickly-firebrick-duck
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-wisteria-rattlesnake.sh
        container: qc.sty_muggy-lemon-bullfrog
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-violet-monster.sh
        container: qc.uni_freaky-viridian-rabbit
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-khaki-havanese.sh
        container: qc.ver_snippy-magenta-spaniel
timeout: 5400
