config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-saffron-lemming.sh
        container: qc.acc_messy-purple-spitz
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gamboge-dragonfly.sh
        container: qc.doc_lousy-azure-pinscher
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-vermilion-ferret.sh
        container: qc.doc_queasy-auburn-affenpinscher
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-turquoise-woodpecker.sh
        container: qc.doc_boozy-carmine-capuchin
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-olive-guppy.sh
        container: qc.lic_skanky-seashell-russel
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magnolia-saola.sh
        container: qc.met_ready-peach-monkey
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-denim-hound.sh
        container: qc.sec_slimy-sangria-albatross
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-champagne-wrasse.sh
        container: qc.sty_hazy-bronze-lemur
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-khaki-rottweiler.sh
        container: qc.sty_messy-cinnamon-goose
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-magnolia-squid.sh
        container: qc.sty_sunny-apricot-owl
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-rust-clam.sh
        container: qc.uni_surly-lilac-mayfly
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-heliotrope-goat.sh
        container: qc.ver_nerdy-olive-weasel
timeout: 5400
