config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-linen-abyssinian.sh
        container: qc.acc_sleepy-wisteria-caracal
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-thistle-magpie.sh
        container: qc.doc_whiny-corn-booby
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-smalt-koala.sh
        container: qc.doc_ready-carmine-sheep
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-denim-turtle.sh
        container: qc.doc_homey-sangria-havanese
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rose-corgi.sh
        container: qc.lic_lovely-buff-owl
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-chartreuse-gopher.sh
        container: qc.sec_smelly-olive-buffalo
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnamon-dormouse.sh
        container: qc.sty_chewy-brass-gecko
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-lavender-buffalo.sh
        container: qc.sty_silly-burgundy-spider
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-asparagus-grouse.sh
        container: qc.sty_sleazy-turquoise-bombay
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lilac-bullfrog.sh
        container: qc.uni_snappy-beige-birman
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-vermilion-forest.sh
        container: qc.ver_nerdy-platinum-zonkey
timeout: 5400
