config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-silver-sparrow.sh
        container: qc.acc_skinny-lilac-tarantula
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-alizarin-wolfhound.sh
        container: qc.doc_shaky-mustard-lynx
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-saffron-chicken.sh
        container: qc.doc_paltry-orange-turtle
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-eggplant-starfish.sh
        container: qc.doc_goopy-indigo-foxhound
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ultramarine-foxhound.sh
        container: qc.lic_snoopy-malachite-liger
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-green-bird.sh
        container: qc.met_paltry-green-chow
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ivory-monster.sh
        container: qc.sec_surly-ochre-lizard
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-green-dachshund.sh
        container: qc.sty_tacky-indigo-opossum
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-amber-dingo.sh
        container: qc.sty_lousy-chartreuse-fousek
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-asparagus-seahorse.sh
        container: qc.sty_geeky-tomato-warthog
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-saffron-liger.sh
        container: qc.uni_smelly-white-macaw
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-buff-quokka.sh
        container: qc.ver_smelly-seashell-monkey
timeout: 5400
