config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ivory-wallaby.sh
        container: qc.acc_hilly-sepia-kiwi
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-white-chinook.sh
        container: qc.doc_flabby-teal-horse
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-teal-cow.sh
        container: qc.doc_queasy-aqua-grouse
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-sangria-dollar.sh
        container: qc.doc_sunny-aqua-anteater
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-black-dragon.sh
        container: qc.lic_shabby-sepia-coral
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-indigo-insect.sh
        container: qc.sec_cloudy-purple-warthog
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-alizarin-neanderthal.sh
        container: qc.sty_skanky-tan-newt
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-bronze-sheepdog.sh
        container: qc.sty_blurry-beige-newfoundland
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-green-albatross.sh
        container: qc.sty_snippy-brass-beagle
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-firebrick-lion.sh
        container: qc.uni_bumpy-rust-mongoose
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-platinum-caterpillar.sh
        container: qc.ver_pretty-cinnabar-mule
timeout: 5400
