config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: main
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-buff-walrus.sh
        container: qc.acc_paltry-beige-bat
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olive-hyena.sh
        container: qc.doc_snippy-linen-gar
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ultramarine-cat.sh
        container: qc.doc_lovely-amaranth-corgi
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-dandelion-spoonbill.sh
        container: qc.doc_cranky-maroon-vulture
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-havanese.sh
        container: qc.lic_ready-platinum-bear
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-numbat.sh
        container: qc.sec_droopy-cornflower-gecko
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-asparagus-hyena.sh
        container: qc.sty_smelly-emerald-ragdoll
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-copper-fish.sh
        container: qc.sty_blurry-ochre-dormouse
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-xanthic-newfoundland.sh
        container: qc.sty_ready-maroon-chimpanzee
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cardinal-crane.sh
        container: qc.uni_boozy-aquamarine-hornet
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-heliotrope-forest.sh
        container: qc.ver_lanky-grey-lynx
timeout: 5400
