config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-corn-angelfish.sh
        container: qc.acc_pretty-yellow-audemer
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-olivine-squirt.sh
        container: qc.doc_geeky-ruby-millipede
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-magnolia-malamute.sh
        container: qc.doc_cranky-saffron-bullfrog
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-eggplant-gecko.sh
        container: qc.doc_fuzzy-champagne-cheetah
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-firebrick-dolphin.sh
        container: qc.lic_zippy-emerald-mayfly
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-pink-chamois.sh
        container: qc.met_chewy-pumpkin-wolfhound
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chartreuse-octopus.sh
        container: qc.sec_snoopy-denim-angora
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-champagne-chamois.sh
        container: qc.sty_sloppy-cardinal-penguin
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gold-scorpion.sh
        container: qc.sty_silly-peach-shark
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-pink-caracal.sh
        container: qc.sty_gamy-lemon-orangutan
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ecru-moorhen.sh
        container: qc.uni_stinky-bistre-reindeer
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-salmon-serval.sh
        container: qc.ver_woozy-saffron-abyssinian
timeout: 5400
