config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clemoule/xtclim:
      branch: notebook_integration
      repo: https://github.com/clemoule/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-turquoise-uakari.sh
        container: qc.acc_stuffy-brown-ladybird
  QC.Doc:
    repos:
      github.com/clemoule/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-seashell-quoll.sh
        container: qc.doc_snoopy-peach-woodpecker
      github.com/clemoule/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magnolia-whippet.sh
        container: qc.doc_tasty-amber-kiwi
      github.com/clemoule/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lime-flamingo.sh
        container: qc.doc_randy-cream-flamingo
  QC.Lic:
    repos:
      github.com/clemoule/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-platinum-forest.sh
        container: qc.lic_wiggy-silver-jellyfish
  QC.Met:
    repos:
      github.com/clemoule/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-gold-javanese.sh
        container: qc.met_sickly-burgundy-orangutan
  QC.Sec:
    repos:
      github.com/clemoule/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerulean-caterpillar.sh
        container: qc.sec_stealthy-fuchsia-caterpillar
  QC.Sty:
    repos:
      github.com/clemoule/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-grey-pig.sh
        container: qc.sty_gimpy-vermilion-bird
      github.com/clemoule/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-copper-dunker.sh
        container: qc.sty_ugly-emerald-bobcat
      github.com/clemoule/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-lilac-harrier.sh
        container: qc.sty_smelly-cerise-emu
  QC.Uni:
    repos:
      github.com/clemoule/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-brass-macaque.sh
        container: qc.uni_tasty-celadon-malamute
  QC.Ver:
    repos:
      github.com/clemoule/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-white-iguana.sh
        container: qc.ver_muzzy-xanthic-leopard
timeout: 5400
