config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lilac-lemming.sh
        container: qc.acc_ugly-brown-monkey
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-chocolate-deer.sh
        container: qc.doc_homely-blue-woodlouse
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-dandelion-reindeer.sh
        container: qc.doc_crappy-cornflower-duck
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-rust-capuchin.sh
        container: qc.doc_paltry-charcoal-turtle
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-periwinkle-lemur.sh
        container: qc.lic_sleazy-sepia-tang
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lemon-heron.sh
        container: qc.met_ugly-lime-dugong
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-linen-llama.sh
        container: qc.sec_homey-jade-owl
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-chestnut-olm.sh
        container: qc.sty_craggy-orange-cow
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-celadon-barnacle.sh
        container: qc.sty_slaphappy-maroon-dragon
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-charcoal-tapir.sh
        container: qc.sty_stinky-chocolate-squid
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-eggplant-bee.sh
        container: qc.uni_queasy-pear-giraffe
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cinnabar-hyrax.sh
        container: qc.ver_grumpy-aquamarine-pinscher
timeout: 5400
