config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/xtclim:
      branch: main
      repo: https://github.com/interTwin-eu/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-brass-mongrel.sh
        container: qc.acc_chewy-chocolate-nightingale
  QC.Doc:
    repos:
      github.com/interTwin-eu/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cinnabar-chinchilla.sh
        container: qc.doc_cloudy-cinnabar-magpie
      github.com/interTwin-eu/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-indigo-spoonbill.sh
        container: qc.doc_skanky-gold-woodpecker
      github.com/interTwin-eu/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aquamarine-mist.sh
        container: qc.doc_crappy-coral-dragon
  QC.Lic:
    repos:
      github.com/interTwin-eu/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-carmine-forest.sh
        container: qc.lic_gloppy-plum-quetzal
  QC.Met:
    repos:
      github.com/interTwin-eu/xtclim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-coral-corgi.sh
        container: qc.met_droopy-gold-bloodhound
  QC.Sec:
    repos:
      github.com/interTwin-eu/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-saffron-kakapo.sh
        container: qc.sec_breezy-cerulean-cougar
  QC.Sty:
    repos:
      github.com/interTwin-eu/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-orchid-eleuth.sh
        container: qc.sty_foggy-apricot-crocodile
      github.com/interTwin-eu/xtclim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-platinum-grasshopper.sh
        container: qc.sty_skimpy-purple-wildebeest
      github.com/interTwin-eu/xtclim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amaranth-horse.sh
        container: qc.sty_stinky-brass-cat
  QC.Uni:
    repos:
      github.com/interTwin-eu/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-brown-capuchin.sh
        container: qc.uni_whiny-lavender-mau
  QC.Ver:
    repos:
      github.com/interTwin-eu/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-red-leopard.sh
        container: qc.ver_shaky-scarlet-cattle
timeout: 5400
