config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cerfacs-globc/xtclim:
      branch: master
      repo: https://github.com/cerfacs-globc/xtclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cerfacs-globc/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-persimmon-woodpecker.sh
        container: qc.acc_cheeky-purple-monkey
  QC.Doc:
    repos:
      github.com/cerfacs-globc/xtclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ultramarine-barb.sh
        container: qc.doc_shaggy-amber-newt
      github.com/cerfacs-globc/xtclim git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-malachite-forest.sh
        container: qc.doc_whiny-champagne-rattlesnake
      github.com/cerfacs-globc/xtclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chocolate-fousek.sh
        container: qc.doc_lovely-taupe-scorpion
  QC.Lic:
    repos:
      github.com/cerfacs-globc/xtclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-pink-donkey.sh
        container: qc.lic_whiny-copper-guppy
  QC.Sec:
    repos:
      github.com/cerfacs-globc/xtclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-taupe-heron.sh
        container: qc.sec_pokey-rose-tuatara
  QC.Sty:
    repos:
      github.com/cerfacs-globc/xtclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-apricot-mongrel.sh
        container: qc.sty_cheeky-persimmon-wrasse
  QC.Uni:
    repos:
      github.com/cerfacs-globc/xtclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-flax-tuatara.sh
        container: qc.uni_cozy-cream-millipede
  QC.Ver:
    repos:
      github.com/cerfacs-globc/xtclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-celadon-earwig.sh
        container: qc.ver_nerdy-beige-otter
timeout: 5400
